### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by ruddfawcett** [ruddfawcett/Notepad#3]
As of now, Notepad is only [21% documented](http://cocoadocs.org/docsets/Notepad/0.2.3) (yikes). Let's get that to 100%.

**Comment by DivineDominion** [comment]
Just adding my 2 cents on this: I think self-documenting code (small types, self-explanatory names) is preferable to 100% documentation coverage because every line of documentation becomes a liability for change. And your types and properties and functions sound good to me, so apart from some obviously useful algorithm explanation, documenting each and every property would be overkill.
